modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]

modId="treemendous"
version="0.2.0"
displayName="Treemendous"
logoFile="treemendous.png"
authors="Ian Rehwinkel"
description='''This mod adds lot's of trees and forests.'''

[[dependencies.treemendous]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.treemendous]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
