modLoader="javafml"
loaderVersion="[31.2.0,)"
license="All rights reserved"

[[mods]]

modId="treemendous"
version="0.4.2"
displayName="Treemendous"
logoFile="treemendous.png"
authors="Ian Rehwinkel"
credits="Thanks to Sebastian Gerdon for making assets and providing inspiration"
description='''
This mod adds a total of 25 new trees with wood, custom foliage and a forest biome for each.
This mod is for the people who want more variation in Minecraft's forests.
'''

[[dependencies.treemendous]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.treemendous]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
